/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConnectMSSQL;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nipun
 */
public class dealercheck extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    String x1="";
    int id=0;
    public dealercheck() {
        initComponents();
        changeColor(show, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));
        clear();

    }
    public dealercheck(int Id) {
        initComponents();
        changeColor(show, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));
        id=Id;
        clear();

    }
    
    public void clear(){
        showroom1.setVisible(false);
        showroom2.setVisible(false);
        showroom3.setVisible(false);
        showroom4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    boolean a=true,b=false;
    
    
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickMenu(JPanel h1, JPanel h2, int numberbool)
    {
        if(numberbool==1)
        {
            h1.setBackground(new Color(25,29,74));
            h2.setBackground(new Color(5,10,46));
        }
        else
        {
            h2.setBackground(new Color(25,29,74));
            h1.setBackground(new Color(5,10,46));
        }
    }
    
    public void hideshow(JPanel menuhide, boolean dashboard)
    {
        if(dashboard==true)
        {
            menuhide.setPreferredSize(new Dimension(50, menuhide.getHeight()));
        }
        else{
            menuhide.setPreferredSize(new Dimension(270, menuhide.getHeight()));
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebutton = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuicon = new javax.swing.JPanel();
        menubutton = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        settingsbutton = new javax.swing.JPanel();
        settings1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        menuhide = new javax.swing.JPanel();
        entry = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        show = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        dashboardveiw = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        showroom1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        showroomtable = new javax.swing.JTable();
        showroom2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        vehicletable = new javax.swing.JTable();
        showroom3 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        accessoriestable = new javax.swing.JTable();
        showroom4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        servicestable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(5, 10, 46));
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closebutton.setBackground(new java.awt.Color(5, 10, 46));
        closebutton.setName(""); // NOI18N
        closebutton.setLayout(new java.awt.BorderLayout());

        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        close1.setName(""); // NOI18N
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close1MouseExited(evt);
            }
        });
        closebutton.add(close1, java.awt.BorderLayout.CENTER);

        close.add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 50, 50));

        header.add(close, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(5, 10, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(5, 10, 52));

        jLabel1.setBackground(new java.awt.Color(5, 10, 52));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CarHub");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 220, 50));

        header.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(270, 450));
        menu.setLayout(new java.awt.BorderLayout());

        menuicon.setBackground(new java.awt.Color(5, 10, 52));
        menuicon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuicon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menubutton.setBackground(new java.awt.Color(5, 10, 46));
        menubutton.setLayout(new java.awt.BorderLayout());

        menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_32px.png"))); // NOI18N
        menu1.setMaximumSize(new java.awt.Dimension(50, 50));
        menu1.setMinimumSize(new java.awt.Dimension(50, 50));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu1MouseExited(evt);
            }
        });
        menubutton.add(menu1, java.awt.BorderLayout.PAGE_START);

        menuicon.add(menubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        settingsbutton.setBackground(new java.awt.Color(5, 10, 46));
        settingsbutton.setLayout(new java.awt.BorderLayout());

        settings1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings_32px.png"))); // NOI18N
        settings1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settings1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settings1MouseExited(evt);
            }
        });
        settingsbutton.add(settings1, java.awt.BorderLayout.PAGE_START);

        menuicon.add(settingsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 40));

        jPanel5.setBackground(new java.awt.Color(5, 10, 46));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuicon.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, -1));

        jPanel6.setBackground(new java.awt.Color(5, 10, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuicon.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        menu.add(menuicon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));

        entry.setBackground(new java.awt.Color(5, 10, 46));
        entry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entryMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(5, 10, 46));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Entry");

        javax.swing.GroupLayout entryLayout = new javax.swing.GroupLayout(entry);
        entry.setLayout(entryLayout);
        entryLayout.setHorizontalGroup(
            entryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        entryLayout.setVerticalGroup(
            entryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(5, 10, 46));
        jPanel8.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        show.setBackground(new java.awt.Color(5, 10, 46));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(5, 10, 46));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Show");

        javax.swing.GroupLayout showLayout = new javax.swing.GroupLayout(show);
        show.setLayout(showLayout);
        showLayout.setHorizontalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showLayout.setVerticalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(5, 10, 46));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuhideLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 350, Short.MAX_VALUE))
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        jComboBox1.setBackground(new java.awt.Color(51, 102, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--NONE--", "Showroom", "Vehicle", "Accessories", "Services" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Data Inserted by You:");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        showroomtable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        showroomtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Showroom Name", "Capacity", "Has Vehicle", "Contact No", "Address"
            }
        ));
        showroomtable.setFocusable(false);
        showroomtable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        showroomtable.setRowHeight(25);
        showroomtable.setSelectionBackground(new java.awt.Color(232, 57, 56));
        showroomtable.setShowVerticalLines(false);
        showroomtable.getTableHeader().setReorderingAllowed(false);
        showroomtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showroomtableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(showroomtable);

        javax.swing.GroupLayout showroom1Layout = new javax.swing.GroupLayout(showroom1);
        showroom1.setLayout(showroom1Layout);
        showroom1Layout.setHorizontalGroup(
            showroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        showroom1Layout.setVerticalGroup(
            showroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );

        vehicletable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        vehicletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vehicle Name", "Model", "Type", "Details", "Cost", "Quantity", "Showroom Id", "Date", "Image Id", "Emi"
            }
        ));
        vehicletable.setFocusable(false);
        vehicletable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        vehicletable.setRowHeight(25);
        vehicletable.setSelectionBackground(new java.awt.Color(232, 57, 56));
        vehicletable.setShowVerticalLines(false);
        vehicletable.getTableHeader().setReorderingAllowed(false);
        vehicletable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicletableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(vehicletable);

        javax.swing.GroupLayout showroom2Layout = new javax.swing.GroupLayout(showroom2);
        showroom2.setLayout(showroom2Layout);
        showroom2Layout.setHorizontalGroup(
            showroom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        showroom2Layout.setVerticalGroup(
            showroom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        accessoriestable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        accessoriestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Accessories Name", "Brand", "Details", "Cost", "Quantity", "Showroom Id", "Date", "Image Id"
            }
        ));
        accessoriestable.setFocusable(false);
        accessoriestable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        accessoriestable.setRowHeight(25);
        accessoriestable.setSelectionBackground(new java.awt.Color(232, 57, 56));
        accessoriestable.setShowVerticalLines(false);
        accessoriestable.getTableHeader().setReorderingAllowed(false);
        accessoriestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accessoriestableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(accessoriestable);

        javax.swing.GroupLayout showroom3Layout = new javax.swing.GroupLayout(showroom3);
        showroom3.setLayout(showroom3Layout);
        showroom3Layout.setHorizontalGroup(
            showroom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        showroom3Layout.setVerticalGroup(
            showroom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        servicestable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        servicestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Service Type", "Details", "Cost", "Showroom Id", "Available"
            }
        ));
        servicestable.setFocusable(false);
        servicestable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        servicestable.setRowHeight(25);
        servicestable.setSelectionBackground(new java.awt.Color(232, 57, 56));
        servicestable.setShowVerticalLines(false);
        servicestable.getTableHeader().setReorderingAllowed(false);
        servicestable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicestableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(servicestable);

        javax.swing.GroupLayout showroom4Layout = new javax.swing.GroupLayout(showroom4);
        showroom4.setLayout(showroom4Layout);
        showroom4Layout.setHorizontalGroup(
            showroom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9)
        );
        showroom4Layout.setVerticalGroup(
            showroom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showroom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showroom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showroom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showroom3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(showroom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showroom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showroom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showroom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout dashboardveiwLayout = new javax.swing.GroupLayout(dashboardveiw);
        dashboardveiw.setLayout(dashboardveiwLayout);
        dashboardveiwLayout.setHorizontalGroup(
            dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardveiwLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardveiwLayout.setVerticalGroup(
            dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardveiwLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(dashboardveiw, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1049, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseEntered
        // TODO add your handling code here:
        changeColor(closebutton, new Color(55,29,74));
    }//GEN-LAST:event_close1MouseEntered

    private void close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseExited
        // TODO add your handling code here:
        changeColor(closebutton, new Color(5,10,46));
    }//GEN-LAST:event_close1MouseExited

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        // TODO add your handling code here:
        clickMenu(menubutton,settingsbutton,1 );
        if(a==true)
        {
            hideshow(menu,a);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }
        else
        {
            hideshow(menu,a);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseEntered
        // TODO add your handling code here:
        
        changeColor(menubutton, new Color(55,29,74));
        changeColor(jPanel6, new Color(247,78,105));
    }//GEN-LAST:event_menu1MouseEntered

    private void menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseExited
        // TODO add your handling code here:
        changeColor(menubutton, new Color(5,10,46));
        changeColor(jPanel6, new Color(5,10,46));
        
    }//GEN-LAST:event_menu1MouseExited

    private void settings1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseEntered
        // TODO add your handling code here:
        changeColor(settingsbutton, new Color(55,29,74));
        changeColor(jPanel5, new Color(8,177,150));
    }//GEN-LAST:event_settings1MouseEntered

    private void settings1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseClicked
        // TODO add your handling code here:
        //clickMenu(settingsbutton,menubutton,1);
    }//GEN-LAST:event_settings1MouseClicked

    private void settings1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseExited
        // TODO add your handling code here:
        changeColor(settingsbutton, new Color(5,10,46));
        changeColor(jPanel5, new Color(5,10,46));
    }//GEN-LAST:event_settings1MouseExited
    
    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        x1 = String.valueOf(jComboBox1.getSelectedItem());
        System.out.println(x1);
        if(x1=="Showroom")
        {
            clear();
            showroom1.setVisible(true);
                String sql="select * from showroom where dealer_Id=?";       
                try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=carhub;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                PreparedStatement pstmt = connection.prepareStatement(sql);
                pstmt.setInt(1,id);
                ResultSet resultSet = pstmt
                .executeQuery();
                while (resultSet.next()){
                    int Id=resultSet.getInt("showroom_Id");
                    String name=resultSet.getString("showroom_Name");
                    int capacity=resultSet.getInt("showroom_Capacity");
                    int has=resultSet.getInt("has_Vehicle");
                    String number=resultSet.getString("contactno");
                    String address=resultSet.getString("address");
                    String data[]={String.valueOf(Id),name,String.valueOf(capacity),String.valueOf(has),number,address};
                    DefaultTableModel tb1model=(DefaultTableModel) showroomtable.getModel();

                    tb1model.addRow(data);
                    
                }                          
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
        else if(x1=="--NONE--")
        {
            clear();
        }
        else if(x1=="Vehicle")
        {
            clear();
            showroom2.setVisible(true);
                String sql="select * from vehicle where dealer_Id=?";       
                try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=carhub;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                PreparedStatement pstmt = connection.prepareStatement(sql);
                pstmt.setInt(1,id);
                ResultSet resultSet = pstmt
                .executeQuery();
                while (resultSet.next()){
                    String carId=String.valueOf(resultSet.getInt("vehicle_Id"));
                String dealerId=String.valueOf(resultSet.getInt("dealer_Id"));
                String carName=resultSet.getString("vehicle_Name");
                String carModel=resultSet.getString("vehicle_Model");
                String carType=resultSet.getString("vehicle_Type");
                String carDetails=resultSet.getString("vehicle_Description");
                String carCost=String.valueOf(resultSet.getInt("vehicle_Cost"));
                int carQuantity=resultSet.getInt("vehicle_Quantity");
                String carShowroom=String.valueOf(resultSet.getInt("showroom_Id"));
                String date=String.valueOf(resultSet.getDate("builddate"));
                String imageid=String.valueOf(resultSet.getInt("imageid"));
                String emi=String.valueOf(resultSet.getInt("emi_available"));
                
                String data[]={carId,carName,carModel,carType,carDetails,carCost,String.valueOf(carQuantity),carShowroom,date,imageid,emi};
                DefaultTableModel tb1model=(DefaultTableModel) vehicletable.getModel();
                
                tb1model.addRow(data);
                    
                }                          
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        else if(x1=="Accessories")
        {
            clear();
            showroom3.setVisible(true);
                String sql="select * from accessories where dealer_Id=?";       
                try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=carhub;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                PreparedStatement pstmt = connection.prepareStatement(sql);
                pstmt.setInt(1,id);
                ResultSet resultSet = pstmt
                .executeQuery();
                while (resultSet.next()){
                    
                String accessoriesId=String.valueOf(resultSet.getInt("accessories_Id"));
                String dealerId=String.valueOf(resultSet.getInt("dealer_Id"));
                String accessoriesName=resultSet.getString("accessories_Name");
                String brandName=resultSet.getString("brand_Name");
                
                String accessoriesDetails=resultSet.getString("accessories_Desc");
                String accessoriesCost=String.valueOf(resultSet.getInt("accessories_Cost"));
                int accessoriesQuantity=resultSet.getInt("accessories_Quantity");
                String accessoriesShowroom=String.valueOf(resultSet.getInt("showroom_Id"));
                String date=String.valueOf(resultSet.getDate("builddate"));
                String imageid=String.valueOf(resultSet.getInt("imageid"));
                
                
                String data[]={accessoriesId,accessoriesName,brandName,accessoriesDetails,accessoriesCost,String.valueOf(accessoriesQuantity),accessoriesShowroom,date,imageid};
                DefaultTableModel tb1model=(DefaultTableModel) accessoriestable.getModel();
                
                tb1model.addRow(data);
                    
                }                          
            }
            catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        else if(x1=="Services")
        {
                clear();
                showroom4.setVisible(true);
                String sql="select * from services where dealer_Id=?";       
                try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=carhub;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                PreparedStatement pstmt = connection.prepareStatement(sql);
                pstmt.setInt(1,id);
                ResultSet resultSet = pstmt
                .executeQuery();
                while (resultSet.next()){
                    
                String serviceId=String.valueOf(resultSet.getInt("service_Id"));
                String serviceType=resultSet.getString("service_Type");   
                String dealerId=String.valueOf(resultSet.getInt("dealer_Id"));
                String serviceDetails=resultSet.getString("service_Desc");
                String serviceCost=String.valueOf(resultSet.getInt("service_Cost"));
                String serviceShowroom=String.valueOf(resultSet.getInt("showroom_Id"));
                String serviceAvailable=resultSet.getString("available");
                
                
                String data[]={serviceId,serviceType,serviceDetails,serviceCost,serviceShowroom,serviceAvailable};
                DefaultTableModel tb1model=(DefaultTableModel) servicestable.getModel();
                
                tb1model.addRow(data);

                }                          
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void entryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryMouseClicked
        // TODO add your handling code here:
        changeColor(entry, new Color(55,29,74));
        changeColor(jPanel8, new Color(247,78,105));

        dealerhome home=new dealerhome(id);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_entryMouseClicked

    private void entryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryMouseEntered
        // TODO add your handling code here:
        changeColor(entry, new Color(55,29,74));
        changeColor(jPanel8, new Color(247,78,105));

    }//GEN-LAST:event_entryMouseEntered

    private void entryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryMouseExited
        // TODO add your handling code here:
        changeColor(entry, new Color(5,10,46));
        changeColor(jPanel8, new Color(5,10,46));
    }//GEN-LAST:event_entryMouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseExited

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        changeColor(show, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));

        dealercheck show=new dealercheck(id);
        show.setVisible(true);
        dispose();
    }//GEN-LAST:event_showMouseClicked

    private void showMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseEntered
        // TODO add your handling code here:
        changeColor(show, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));

    }//GEN-LAST:event_showMouseEntered

    private void showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_showMouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseExited

    private void servicestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicestableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_servicestableMouseClicked

    private void accessoriestableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessoriestableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accessoriestableMouseClicked

    private void vehicletableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicletableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicletableMouseClicked

    private void showroomtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showroomtableMouseClicked
        // TODO add your handling code here:
        /*JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String s=source.getModel().getValueAt(row, column)+"";

        JOptionPane.showMessageDialog(null, s);*/
    }//GEN-LAST:event_showroomtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealercheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealercheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealercheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealercheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dealercheck().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accessoriestable;
    private javax.swing.JPanel close;
    private javax.swing.JLabel close1;
    private javax.swing.JPanel closebutton;
    private javax.swing.JPanel dashboardveiw;
    private javax.swing.JPanel entry;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JPanel menubutton;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel menuicon;
    private javax.swing.JTable servicestable;
    private javax.swing.JLabel settings1;
    private javax.swing.JPanel settingsbutton;
    private javax.swing.JPanel show;
    private javax.swing.JPanel showroom1;
    private javax.swing.JPanel showroom2;
    private javax.swing.JPanel showroom3;
    private javax.swing.JPanel showroom4;
    private javax.swing.JTable showroomtable;
    private javax.swing.JTable vehicletable;
    // End of variables declaration//GEN-END:variables
}
