/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConnectMSSQL;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nipun
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    int Id,flag=0;
    String Page,Nid,Name;
    public login() {
        
        initComponents();
        
    }
    
    public login(String page,int id) {
        initComponents();
        Page=page;
        Id=id;
        receiptView.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    boolean a=true,b=false;
    
    
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickMenu(JPanel h1, JPanel h2, int numberbool)
    {
        if(numberbool==1)
        {
            h1.setBackground(new Color(25,29,74));
            h2.setBackground(new Color(5,10,46));
        }
        else
        {
            h2.setBackground(new Color(25,29,74));
            h1.setBackground(new Color(5,10,46));
        }
    }
    
    public void hideshow(JPanel menuhide, boolean dashboard)
    {
        if(dashboard==true)
        {
            menuhide.setPreferredSize(new Dimension(50, menuhide.getHeight()));
        }
        else{
            menuhide.setPreferredSize(new Dimension(270, menuhide.getHeight()));
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        closebutton = new javax.swing.JPanel();
        close1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuicon = new javax.swing.JPanel();
        menubutton = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        settingsbutton = new javax.swing.JPanel();
        settings1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        menuhide = new javax.swing.JPanel();
        allCar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        accessories = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        services = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        dashboardveiw = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        nid = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptView = new javax.swing.JTextArea();
        receipt = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setLayout(new java.awt.BorderLayout());

        close.setBackground(new java.awt.Color(5, 10, 46));
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closebutton.setBackground(new java.awt.Color(5, 10, 46));
        closebutton.setName(""); // NOI18N
        closebutton.setLayout(new java.awt.BorderLayout());

        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        close1.setName(""); // NOI18N
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close1MouseExited(evt);
            }
        });
        closebutton.add(close1, java.awt.BorderLayout.CENTER);

        close.add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 50, 50));

        header.add(close, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(5, 10, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(5, 10, 52));

        jLabel1.setBackground(new java.awt.Color(5, 10, 52));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CarHub");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 220, 50));

        header.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(270, 450));
        menu.setLayout(new java.awt.BorderLayout());

        menuicon.setBackground(new java.awt.Color(5, 10, 52));
        menuicon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuicon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menubutton.setBackground(new java.awt.Color(5, 10, 46));
        menubutton.setLayout(new java.awt.BorderLayout());

        menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_32px.png"))); // NOI18N
        menu1.setMaximumSize(new java.awt.Dimension(50, 50));
        menu1.setMinimumSize(new java.awt.Dimension(50, 50));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu1MouseExited(evt);
            }
        });
        menubutton.add(menu1, java.awt.BorderLayout.PAGE_START);

        menuicon.add(menubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        settingsbutton.setBackground(new java.awt.Color(5, 10, 46));
        settingsbutton.setLayout(new java.awt.BorderLayout());

        settings1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings_32px.png"))); // NOI18N
        settings1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settings1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settings1MouseExited(evt);
            }
        });
        settingsbutton.add(settings1, java.awt.BorderLayout.PAGE_START);

        menuicon.add(settingsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 40));

        jPanel5.setBackground(new java.awt.Color(5, 10, 46));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuicon.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, -1));

        jPanel6.setBackground(new java.awt.Color(5, 10, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuicon.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        menu.add(menuicon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));

        allCar.setBackground(new java.awt.Color(5, 10, 46));
        allCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allCarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allCarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allCarMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(5, 10, 46));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All Cars");

        javax.swing.GroupLayout allCarLayout = new javax.swing.GroupLayout(allCar);
        allCar.setLayout(allCarLayout);
        allCarLayout.setHorizontalGroup(
            allCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allCarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        allCarLayout.setVerticalGroup(
            allCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allCarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(5, 10, 46));
        jPanel8.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        accessories.setBackground(new java.awt.Color(5, 10, 46));
        accessories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accessoriesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accessoriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accessoriesMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(5, 10, 46));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Accessories");

        javax.swing.GroupLayout accessoriesLayout = new javax.swing.GroupLayout(accessories);
        accessories.setLayout(accessoriesLayout);
        accessoriesLayout.setHorizontalGroup(
            accessoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessoriesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        accessoriesLayout.setVerticalGroup(
            accessoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(5, 10, 46));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(5, 10, 46));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        services.setBackground(new java.awt.Color(5, 10, 46));
        services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servicesMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(5, 10, 46));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Services");

        javax.swing.GroupLayout servicesLayout = new javax.swing.GroupLayout(services);
        services.setLayout(servicesLayout);
        servicesLayout.setHorizontalGroup(
            servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        servicesLayout.setVerticalGroup(
            servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        register.setBackground(new java.awt.Color(5, 10, 46));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(5, 10, 46));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Register");

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(5, 10, 46));
        jPanel11.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(allCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(accessories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(services, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuhideLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(allCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(accessories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(services, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("You have to confirm your id in before buy!");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NID:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Password:");

        nid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(204, 0, 204));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        receiptView.setColumns(20);
        receiptView.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        receiptView.setRows(5);
        jScrollPane1.setViewportView(receiptView);

        receipt.setText("Print Receipt");
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
        });
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel13.setText("BACK");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboardveiwLayout = new javax.swing.GroupLayout(dashboardveiw);
        dashboardveiw.setLayout(dashboardveiwLayout);
        dashboardveiwLayout.setHorizontalGroup(
            dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardveiwLayout.createSequentialGroup()
                .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dashboardveiwLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashboardveiwLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(submit))
                            .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(dashboardveiwLayout.createSequentialGroup()
                                    .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(29, 29, 29)
                                    .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(password)
                                        .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(dashboardveiwLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(receipt)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashboardveiwLayout.setVerticalGroup(
            dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardveiwLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dashboardveiwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardveiwLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(receipt)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardveiwLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(dashboardveiwLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        getContentPane().add(dashboardveiw, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1049, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseEntered
        // TODO add your handling code here:
        changeColor(closebutton, new Color(55,29,74));
    }//GEN-LAST:event_close1MouseEntered

    private void close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseExited
        // TODO add your handling code here:
        changeColor(closebutton, new Color(5,10,46));
    }//GEN-LAST:event_close1MouseExited

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        // TODO add your handling code here:
        clickMenu(menubutton,settingsbutton,1 );
        if(a==true)
        {
            hideshow(menu,a);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }
        else
        {
            hideshow(menu,a);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseEntered
        // TODO add your handling code here:
        
        changeColor(menubutton, new Color(55,29,74));
        changeColor(jPanel6, new Color(247,78,105));
    }//GEN-LAST:event_menu1MouseEntered

    private void menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseExited
        // TODO add your handling code here:
        changeColor(menubutton, new Color(5,10,46));
        changeColor(jPanel6, new Color(5,10,46));
        
    }//GEN-LAST:event_menu1MouseExited

    private void settings1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseEntered
        // TODO add your handling code here:
        changeColor(settingsbutton, new Color(55,29,74));
        changeColor(jPanel5, new Color(8,177,150));
    }//GEN-LAST:event_settings1MouseEntered

    private void settings1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseClicked
        // TODO add your handling code here:
        //clickMenu(settingsbutton,menubutton,1);
    }//GEN-LAST:event_settings1MouseClicked

    private void settings1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings1MouseExited
        // TODO add your handling code here:
        changeColor(settingsbutton, new Color(5,10,46));
        changeColor(jPanel5, new Color(5,10,46));
    }//GEN-LAST:event_settings1MouseExited

    private void allCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allCarMouseClicked
        // TODO add your handling code here:
        changeColor(allCar, new Color(55,29,74));
        changeColor(jPanel8, new Color(247,78,105));
        
        allcar all=new allcar();
        all.setVisible(true);
        dispose();
    }//GEN-LAST:event_allCarMouseClicked

    private void allCarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allCarMouseEntered
        // TODO add your handling code here:
        changeColor(allCar, new Color(55,29,74));
        changeColor(jPanel8, new Color(247,78,105));
        
    }//GEN-LAST:event_allCarMouseEntered

    private void allCarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allCarMouseExited
        // TODO add your handling code here:
        changeColor(allCar, new Color(5,10,46));
        changeColor(jPanel8, new Color(5,10,46));
    }//GEN-LAST:event_allCarMouseExited
    
    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseExited

    private void accessoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessoriesMouseClicked
        // TODO add your handling code here:
        changeColor(accessories, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));
        accessories acc=new accessories();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_accessoriesMouseClicked

    private void accessoriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessoriesMouseEntered
        // TODO add your handling code here:
        changeColor(accessories, new Color(55,29,74));
        changeColor(jPanel9, new Color(247,78,105));
    }//GEN-LAST:event_accessoriesMouseEntered

    private void accessoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessoriesMouseExited
        // TODO add your handling code here:
        changeColor(accessories, new Color(5,10,46));
        changeColor(jPanel9, new Color(5,10,46));
    }//GEN-LAST:event_accessoriesMouseExited

    private void servicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicesMouseClicked
        // TODO add your handling code here:
        changeColor(services, new Color(55,29,74));
        changeColor(jPanel10, new Color(247,78,105));
        
        services ser=new services();
        ser.setVisible(true);
        dispose();
    }//GEN-LAST:event_servicesMouseClicked

    private void servicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicesMouseEntered
        // TODO add your handling code here:
        changeColor(services, new Color(55,29,74));
        changeColor(jPanel10, new Color(247,78,105));
    }//GEN-LAST:event_servicesMouseEntered

    private void servicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicesMouseExited
        // TODO add your handling code here:
        changeColor(services, new Color(5,10,46));
        changeColor(jPanel10, new Color(5,10,46));
    }//GEN-LAST:event_servicesMouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        changeColor(register, new Color(55,29,74));
        changeColor(jPanel11, new Color(247,78,105));
        
        register reg=new register();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerMouseClicked

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
        changeColor(register, new Color(55,29,74));
        changeColor(jPanel11, new Color(247,78,105));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        // TODO add your handling code here:
        changeColor(register, new Color(5,10,46));
        changeColor(jPanel11, new Color(5,10,46));
    }//GEN-LAST:event_registerMouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseExited

    private void nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String sql="select * from customer where customer_Nid=? and password=?";
        String id = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=carhub;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            Statement statement = connection.createStatement();
            PreparedStatement pstmt = connection.prepareStatement(sql);
            Nid=nid.getText();
            pstmt.setString(1,nid.getText());
            pstmt.setString(2,String.valueOf(password.getPassword()));
            //ResultSet resultSet = statement
            //        .executeQuery(sql);
            ResultSet resultSet = pstmt
                    .executeQuery();
            
            while (resultSet.next()) {
                
                /*System.out.println("Dealer NAME:" + 
                        resultSet.getString("dealername"));*/
                Name=resultSet.getString("customer_Name");
                id="1";                
            }
            if(id!="1")
            {
                JOptionPane.showMessageDialog(null,"You are not Registered!");
            }
            else if(id=="1")
            {   
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (null, "Confirm receipt?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    
                submit.setEnabled(false);
                if(Page=="accessories")
                {
                    int accessoriesId=0,dealerId=0,accessoriesCost=0, accessoriesQuantity=0,accessoriesShowroom=0,imageid=0;
                    String accessoriesName="",brandName,accessoriesDetails,date;
                    sql="select * from accessories where accessories_Id=?";
                    pstmt = connection.prepareStatement(sql);
                    pstmt.setString(1,String.valueOf(Id));
                    resultSet = pstmt
                    .executeQuery();
                    while (resultSet.next()) {
                
                            /*System.out.println("Dealer NAME:" + 
                                    resultSet.getString("dealername"));*/
                            accessoriesId=resultSet.getInt("accessories_Id");
                            dealerId=resultSet.getInt("dealer_Id");
                            accessoriesName=resultSet.getString("accessories_Name");
                            brandName=resultSet.getString("brand_Name");

                            accessoriesDetails=resultSet.getString("accessories_Desc");
                            accessoriesCost=resultSet.getInt("accessories_Cost");
                            accessoriesQuantity=resultSet.getInt("accessories_Quantity");
                            accessoriesShowroom=resultSet.getInt("showroom_Id");
                            date=String.valueOf(resultSet.getDate("builddate"));
                            imageid=resultSet.getInt("imageid");                            
                        }
                    Timestamp current=new Timestamp(System.currentTimeMillis());
                    sql="insert into order_Details(order_Id,order_Type,type_Id,customer_Nid,cost,order_date,delivery_date,emi_Check,cost_Given) Values(?,?,?,?,?,?,?,?,?)";
                    pstmt = connection.prepareStatement(sql);
                    try {
                        String uniqueID = UUID.randomUUID().toString();
                        pstmt.setString(1,uniqueID);
                        pstmt.setString(2,Page);
                        pstmt.setInt(3,Id);
                        pstmt.setString(4,Nid);
                       
                        pstmt.setInt(5,accessoriesCost);
                        pstmt.setTimestamp(6,current);
                        pstmt.setTimestamp(7,current);
                        pstmt.setString(8,"Not Available");
                        pstmt.setInt(9,accessoriesCost);

                        //ResultSet resultSet = statement
                        //        .executeQuery(sql);
                        pstmt.execute();
                        receiptView.append("\t\t CarHub \n\n"+
                        "Order Id:\t\t"+uniqueID+"\n\n"+
                        "Customer Name:\t\t"+Name+"\n\n"+
                        "Order Name:\t\t"+accessoriesName+"\n\n"+
                        "Order Type:\t\t"+"Accessories"+"\n\n"+
                        "Showroom:\t\t"+accessoriesShowroom+"\n\n"+
                        "Order Date:\t\t"+current+"\n\n"+
                        "Delivery Date:\t\t"+current+"\n\n"+
                        "Cost:\t\t\t"+accessoriesCost+"/=\n\n");
                        JOptionPane.showMessageDialog(this, "Purchased!");

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    
                    accessoriesQuantity=accessoriesQuantity-1;
                    sql="Update accessories set accessories_Quantity=? where accessories_Id=?";
                    pstmt = connection.prepareStatement(sql);
                    try {
                        pstmt.setString(1,String.valueOf(accessoriesQuantity));
                        pstmt.setString(2,String.valueOf(Id));

                        //ResultSet resultSet = statement
                        //        .executeQuery(sql);
                        pstmt.execute();
                       
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
             
                }
                else if(Page=="cars")
                {
                    int carId=0,dealerId=0,carCost=0, carQuantity=0,carShowroom=0,imageid=0,emi=0;
                    String carName="",carModel,carType,carDetails,date;
                    sql="select * from vehicle where vehicle_Id=?";
                    pstmt = connection.prepareStatement(sql);
                    pstmt.setString(1,String.valueOf(Id));
                    resultSet = pstmt
                    .executeQuery();
                    while (resultSet.next()) {
                
                            /*System.out.println("Dealer NAME:" + 
                                    resultSet.getString("dealername"));*/
                            carId=resultSet.getInt("vehicle_Id");
                            dealerId=resultSet.getInt("dealer_Id");
                            carName=resultSet.getString("vehicle_Name");
                            carModel=resultSet.getString("vehicle_Model");
                            carType=resultSet.getString("vehicle_Type");
                            carDetails=resultSet.getString("vehicle_Description");
                            carCost=resultSet.getInt("vehicle_Cost");
                            carQuantity=resultSet.getInt("vehicle_Quantity");
                            carShowroom=resultSet.getInt("showroom_Id");
                            date=String.valueOf(resultSet.getDate("builddate"));
                            imageid=resultSet.getInt("imageid");
                            emi=resultSet.getInt("emi_available");
                            
                        }
                    Timestamp current=new Timestamp(System.currentTimeMillis());
                    sql="insert into order_Details(order_Id,order_Type,type_Id, customer_Nid,cost,order_date,delivery_date,emi_Check,emi_Months,cost_Given) Values(?,?,?,?,?,?,?,?,?,?)";
                    pstmt = connection.prepareStatement(sql);
                    try {
                        String uniqueID = UUID.randomUUID().toString();
                        pstmt.setString(1,uniqueID);
                        pstmt.setString(2,Page);
                        pstmt.setInt(3,Id);
                        pstmt.setString(4,Nid);
                        pstmt.setInt(5,carCost);
                        pstmt.setTimestamp(6,current);
                        pstmt.setTimestamp(7,current);
                        pstmt.setString(8,"Available");
                        pstmt.setInt(9,emi);
                        pstmt.setInt(10,carCost);

                        //ResultSet resultSet = statement
                        //        .executeQuery(sql);
                        pstmt.execute();
                        receiptView.append("\t\t CarHub \n\n"+
                        "Order Id:\t\t"+uniqueID+"\n\n"+
                        "Customer Name:\t\t"+Name+"\n\n"+
                        "Order Name:\t\t"+carName+"\n\n"+
                        "Order Type:\t\t"+"Car"+"\n\n"+
                        "Showroom:\t\t"+carShowroom+"\n\n"+
                        "Order Date:\t\t"+current+"\n\n"+
                        "Delivery Date:\t\t"+current+"\n\n"+
                        "Cost:\t\t\t"+carCost+"/=\n\n"+
                        "Emi:\t\t\t"+emi+"\n\n"+
                        "Total Cost:\t\t"+carCost+"/=\n\n"
                                );
                        JOptionPane.showMessageDialog(this, "Purchased!");

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    carQuantity=carQuantity-1;
                    sql="Update vehicle set vehicle_Quantity=? where vehicle_Id=?";
                    pstmt = connection.prepareStatement(sql);
                    try {
                        pstmt.setString(1,String.valueOf(carQuantity));
                        pstmt.setString(2,String.valueOf(Id));

                        //ResultSet resultSet = statement
                        //        .executeQuery(sql);
                        pstmt.execute();
                       
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
             
                    }
                    else if(Page=="services")
                    {
                        int serviceId=0,dealerId=0,serviceCost=0,serviceShowroom=0;
                        String serviceType="",serviceDetails;
                        sql="select * from services where service_Id=?";
                        pstmt = connection.prepareStatement(sql);
                        pstmt.setString(1,String.valueOf(Id));
                        resultSet = pstmt
                        .executeQuery();
                        while (resultSet.next()) {
                
                            /*System.out.println("Dealer NAME:" + 
                                    resultSet.getString("dealername"));*/
                            serviceId=resultSet.getInt("service_Id");
                            dealerId=resultSet.getInt("dealer_Id");
                            serviceType=resultSet.getString("service_Type");
                            serviceDetails=resultSet.getString("service_Desc");
                            serviceCost=resultSet.getInt("service_Cost");
                            serviceShowroom=resultSet.getInt("showroom_Id");
                            
                        }
                        Timestamp current=new Timestamp(System.currentTimeMillis());
                        sql="insert into order_Details(order_Id,order_Type,type_Id,customer_Nid,cost,order_date,delivery_date,emi_Check,cost_Given) Values(?,?,?,?,?,?,?,?,?)";
                        pstmt = connection.prepareStatement(sql);
                        try {
                            String uniqueID = UUID.randomUUID().toString();
                            pstmt.setString(1,uniqueID);
                            pstmt.setString(2,Page);
                            pstmt.setInt(3,Id);
                            pstmt.setString(4,Nid);
                            //pstmt.setInt(5,serviceShowroom);
                            pstmt.setInt(5,serviceCost);
                            pstmt.setTimestamp(6,current);
                            pstmt.setTimestamp(7,current);
                            pstmt.setString(8,"Not Available");
                            pstmt.setInt(9,serviceCost);

                            //ResultSet resultSet = statement
                            //        .executeQuery(sql);
                            pstmt.execute();
                            receiptView.append("\t\t CarHub \n\n"+
                            "Order Id:\t\t"+uniqueID+"\n\n"+
                            "Customer Name:\t\t"+Name+"\n\n"+
                            "Order Name:\t\t"+serviceType+"\n\n"+
                            "Order Type:\t\t"+"Services"+"\n\n"+
                            "Showroom:\t\t"+serviceShowroom+"\n\n"+
                            "Order Date:\t\t"+current+"\n\n"+
                            "Delivery Date:\t\t"+current+"\n\n"+
                            "Cost:\t\t\t"+serviceCost+"/=\n\n"
                                    );
                            JOptionPane.showMessageDialog(this, "Purchased!");

                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                    }
                    
                }
                    
               
                else
                {
                    
                }
            }
            
            } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptActionPerformed

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
        try {
            // TODO add your handling code here:
            receiptView.print();
        } catch (PrinterException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_receiptMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        homaepage1 hm = new homaepage1();
        hm.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessories;
    private javax.swing.JPanel allCar;
    private javax.swing.JPanel close;
    private javax.swing.JLabel close1;
    private javax.swing.JPanel closebutton;
    private javax.swing.JPanel dashboardveiw;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menu1;
    private javax.swing.JPanel menubutton;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel menuicon;
    private javax.swing.JTextField nid;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton receipt;
    private javax.swing.JTextArea receiptView;
    private javax.swing.JPanel register;
    private javax.swing.JPanel services;
    private javax.swing.JLabel settings1;
    private javax.swing.JPanel settingsbutton;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
